version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@tree-house.com
      - PGADMIN_DEFAULT_PASSWORD=dev
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  app:
    build:
      context: ../app/backend
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000 --settings=tree_house.conf.dev
    volumes:
      - ../app/backend:/code
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  worker:
    restart: always
    build:
      context: ../app/backend
      dockerfile: docker/docker_files/Dockerfile
    command: celery -A tree_house worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ../app/backend:/code
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
      - app

  beat:
    build:
      context: ../app/backend
      dockerfile: docker/docker_files/Dockerfile
    command: celery -A tree_house beat -l info
    volumes:
      - ../app/backend:/code
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
      - app


  flower:
    build:
      context: ../app/backend
      dockerfile: docker/docker_files/Dockerfile
    command: celery -A tree_house flower  --broker=redis://redis:6379
    ports:
      - 5555:5555
    env_file:
      - ../.env
    depends_on:
      - db
      - app
      - redis
      - worker



volumes:
  pg:
  pgadmin:

